
import { User, AssessmentQuestion } from "../types";

// Mock users
export const mockUsers: User[] = [
  {
    id: "1",
    username: "alex_fit",
    email: "alex@example.com",
    displayName: "Alex Fitness",
    profileImage: "https://i.pravatar.cc/300?img=1",
    bio: "Fitness enthusiast, software developer, and avid reader.",
    level: 7,
    joinDate: new Date("2023-01-15"),
    lastActive: new Date(),
    streakDays: 15,
    attributes: [
      {
        type: "strength",
        name: "Strength",
        level: 8,
        xpCurrent: 50,
        xpRequired: 800,
        color: "#F45B69",
        icon: "dumbbell",
        subAttributes: [
          {
            name: "power",
            level: 9,
            description: "Raw physical strength",
            xpCurrent: 30,
            xpRequired: 900,
          },
          {
            name: "endurance",
            level: 7,
            description: "Physical stamina and endurance",
            xpCurrent: 40,
            xpRequired: 700,
          },
          {
            name: "agility",
            level: 8,
            description: "Speed, flexibility and coordination",
            xpCurrent: 60,
            xpRequired: 800,
          },
          {
            name: "durability",
            level: 8,
            description: "Resistance to injury and quick recovery",
            xpCurrent: 70,
            xpRequired: 800,
          },
        ],
      },
      {
        type: "health",
        name: "Health",
        level: 8,
        xpCurrent: 80,
        xpRequired: 800,
        color: "#17B978",
        icon: "heart",
        subAttributes: [
          {
            name: "physical",
            level: 9,
            description: "Physical health and wellbeing",
            xpCurrent: 90,
            xpRequired: 900,
          },
          {
            name: "mental",
            level: 7,
            description: "Mental health and emotional stability",
            xpCurrent: 50,
            xpRequired: 700,
          },
          {
            name: "nutrition",
            level: 8,
            description: "Diet and nutritional habits",
            xpCurrent: 60,
            xpRequired: 800,
          },
          {
            name: "sleep",
            level: 7,
            description: "Quality and quantity of sleep",
            xpCurrent: 40,
            xpRequired: 700,
          },
          {
            name: "balance",
            level: 7,
            description: "Work-life balance and stress management",
            xpCurrent: 30,
            xpRequired: 700,
          },
        ],
      },
      {
        type: "knowledge",
        name: "Knowledge",
        level: 6,
        xpCurrent: 40,
        xpRequired: 600,
        color: "#4F86F7",
        icon: "book",
        subAttributes: [
          {
            name: "academic",
            level: 6,
            description: "Academic knowledge and formal education",
            xpCurrent: 40,
            xpRequired: 600,
          },
          {
            name: "practical",
            level: 7,
            description: "Practical skills and applied knowledge",
            xpCurrent: 30,
            xpRequired: 700,
          },
          {
            name: "world",
            level: 5,
            description: "Understanding of the world and current events",
            xpCurrent: 50,
            xpRequired: 500,
          },
        ],
      },
      {
        type: "intelligence",
        name: "Intelligence",
        level: 7,
        xpCurrent: 60,
        xpRequired: 700,
        color: "#A64AC9",
        icon: "brain",
        subAttributes: [
          {
            name: "creativity",
            level: 8,
            description: "Creative thinking and problem solving",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "social",
            level: 6,
            description: "Social intelligence and emotional understanding",
            xpCurrent: 40,
            xpRequired: 600,
          },
          {
            name: "analytical",
            level: 7,
            description: "Analytical thinking and logical reasoning",
            xpCurrent: 60,
            xpRequired: 700,
          },
          {
            name: "foresight",
            level: 6,
            description: "Anticipation and strategic planning",
            xpCurrent: 50,
            xpRequired: 600,
          },
          {
            name: "influence",
            level: 7,
            description: "Ability to influence and persuade others",
            xpCurrent: 30,
            xpRequired: 700,
          },
        ],
      },
    ],
    friends: ["2", "3"],
    isOnline: true,
  },
  {
    id: "2",
    username: "maria_smart",
    email: "maria@example.com",
    displayName: "Maria Intellect",
    profileImage: "https://i.pravatar.cc/300?img=5",
    bio: "Astrophysicist, chess player, and language enthusiast.",
    level: 8,
    joinDate: new Date("2022-11-20"),
    lastActive: new Date(),
    streakDays: 30,
    attributes: [
      {
        type: "intelligence",
        name: "Intelligence",
        level: 9,
        xpCurrent: 80,
        xpRequired: 900,
        color: "#A64AC9",
        icon: "brain",
        subAttributes: [
          {
            name: "creativity",
            level: 8,
            description: "Creative thinking and problem solving",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "social",
            level: 7,
            description: "Social intelligence and emotional understanding",
            xpCurrent: 60,
            xpRequired: 700,
          },
          {
            name: "analytical",
            level: 10,
            description: "Analytical thinking and logical reasoning",
            xpCurrent: 90,
            xpRequired: 1000,
          },
          {
            name: "foresight",
            level: 9,
            description: "Anticipation and strategic planning",
            xpCurrent: 80,
            xpRequired: 900,
          },
          {
            name: "influence",
            level: 8,
            description: "Ability to influence and persuade others",
            xpCurrent: 70,
            xpRequired: 800,
          },
        ],
      },
      {
        type: "knowledge",
        name: "Knowledge",
        level: 9,
        xpCurrent: 90,
        xpRequired: 900,
        color: "#4F86F7",
        icon: "book",
        subAttributes: [
          {
            name: "academic",
            level: 10,
            description: "Academic knowledge and formal education",
            xpCurrent: 90,
            xpRequired: 1000,
          },
          {
            name: "practical",
            level: 8,
            description: "Practical skills and applied knowledge",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "world",
            level: 9,
            description: "Understanding of the world and current events",
            xpCurrent: 80,
            xpRequired: 900,
          },
        ],
      },
      {
        type: "health",
        name: "Health",
        level: 7,
        xpCurrent: 60,
        xpRequired: 700,
        color: "#17B978",
        icon: "heart",
        subAttributes: [
          {
            name: "physical",
            level: 6,
            description: "Physical health and wellbeing",
            xpCurrent: 50,
            xpRequired: 600,
          },
          {
            name: "mental",
            level: 8,
            description: "Mental health and emotional stability",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "nutrition",
            level: 7,
            description: "Diet and nutritional habits",
            xpCurrent: 60,
            xpRequired: 700,
          },
          {
            name: "sleep",
            level: 6,
            description: "Quality and quantity of sleep",
            xpCurrent: 50,
            xpRequired: 600,
          },
          {
            name: "balance",
            level: 8,
            description: "Work-life balance and stress management",
            xpCurrent: 70,
            xpRequired: 800,
          },
        ],
      },
      {
        type: "strength",
        name: "Strength",
        level: 5,
        xpCurrent: 40,
        xpRequired: 500,
        color: "#F45B69",
        icon: "dumbbell",
        subAttributes: [
          {
            name: "power",
            level: 4,
            description: "Raw physical strength",
            xpCurrent: 30,
            xpRequired: 400,
          },
          {
            name: "endurance",
            level: 5,
            description: "Physical stamina and endurance",
            xpCurrent: 40,
            xpRequired: 500,
          },
          {
            name: "agility",
            level: 6,
            description: "Speed, flexibility and coordination",
            xpCurrent: 50,
            xpRequired: 600,
          },
          {
            name: "durability",
            level: 5,
            description: "Resistance to injury and quick recovery",
            xpCurrent: 40,
            xpRequired: 500,
          },
        ],
      },
    ],
    friends: ["1", "4"],
    isOnline: false,
  },
  {
    id: "3",
    username: "healthy_sam",
    email: "sam@example.com",
    displayName: "Sam Wellness",
    profileImage: "https://i.pravatar.cc/300?img=12",
    bio: "Nutritionist, yoga instructor, and mental health advocate.",
    level: 6,
    joinDate: new Date("2023-03-05"),
    lastActive: new Date(),
    streakDays: 10,
    attributes: [
      {
        type: "health",
        name: "Health",
        level: 9,
        xpCurrent: 80,
        xpRequired: 900,
        color: "#17B978",
        icon: "heart",
        subAttributes: [
          {
            name: "physical",
            level: 8,
            description: "Physical health and wellbeing",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "mental",
            level: 9,
            description: "Mental health and emotional stability",
            xpCurrent: 80,
            xpRequired: 900,
          },
          {
            name: "nutrition",
            level: 10,
            description: "Diet and nutritional habits",
            xpCurrent: 90,
            xpRequired: 1000,
          },
          {
            name: "sleep",
            level: 9,
            description: "Quality and quantity of sleep",
            xpCurrent: 80,
            xpRequired: 900,
          },
          {
            name: "balance",
            level: 10,
            description: "Work-life balance and stress management",
            xpCurrent: 90,
            xpRequired: 1000,
          },
        ],
      },
      {
        type: "strength",
        name: "Strength",
        level: 7,
        xpCurrent: 60,
        xpRequired: 700,
        color: "#F45B69",
        icon: "dumbbell",
        subAttributes: [
          {
            name: "power",
            level: 6,
            description: "Raw physical strength",
            xpCurrent: 50,
            xpRequired: 600,
          },
          {
            name: "endurance",
            level: 8,
            description: "Physical stamina and endurance",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "agility",
            level: 8,
            description: "Speed, flexibility and coordination",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "durability",
            level: 7,
            description: "Resistance to injury and quick recovery",
            xpCurrent: 60,
            xpRequired: 700,
          },
        ],
      },
      {
        type: "intelligence",
        name: "Intelligence",
        level: 6,
        xpCurrent: 50,
        xpRequired: 600,
        color: "#A64AC9",
        icon: "brain",
        subAttributes: [
          {
            name: "creativity",
            level: 6,
            description: "Creative thinking and problem solving",
            xpCurrent: 50,
            xpRequired: 600,
          },
          {
            name: "social",
            level: 8,
            description: "Social intelligence and emotional understanding",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "analytical",
            level: 5,
            description: "Analytical thinking and logical reasoning",
            xpCurrent: 40,
            xpRequired: 500,
          },
          {
            name: "foresight",
            level: 5,
            description: "Anticipation and strategic planning",
            xpCurrent: 40,
            xpRequired: 500,
          },
          {
            name: "influence",
            level: 7,
            description: "Ability to influence and persuade others",
            xpCurrent: 60,
            xpRequired: 700,
          },
        ],
      },
      {
        type: "knowledge",
        name: "Knowledge",
        level: 7,
        xpCurrent: 60,
        xpRequired: 700,
        color: "#4F86F7",
        icon: "book",
        subAttributes: [
          {
            name: "academic",
            level: 7,
            description: "Academic knowledge and formal education",
            xpCurrent: 60,
            xpRequired: 700,
          },
          {
            name: "practical",
            level: 8,
            description: "Practical skills and applied knowledge",
            xpCurrent: 70,
            xpRequired: 800,
          },
          {
            name: "world",
            level: 6,
            description: "Understanding of the world and current events",
            xpCurrent: 50,
            xpRequired: 600,
          },
        ],
      },
    ],
    friends: ["1"],
    isOnline: true,
  },
];

// Assessment questions
export const assessmentQuestions: AssessmentQuestion[] = [
  // Knowledge questions
  {
    id: "k1",
    attributeType: "knowledge",
    question: "How much time do you typically spend reading or learning per week?",
    options: [
      { text: "Less than 1 hour", value: 1 },
      { text: "1-3 hours", value: 2 },
      { text: "4-7 hours", value: 3 },
      { text: "8-14 hours", value: 4 },
      { text: "15+ hours", value: 5 },
    ],
  },
  {
    id: "k2",
    attributeType: "knowledge",
    question: "How would you rate your general academic knowledge?",
    options: [
      { text: "Below average", value: 1 },
      { text: "Average", value: 2 },
      { text: "Above average", value: 3 },
      { text: "Excellent", value: 4 },
      { text: "Expert/Specialized", value: 5 },
    ],
  },
  {
    id: "k3",
    attributeType: "knowledge",
    question: "How comfortable are you applying what you've learned to practical situations?",
    options: [
      { text: "Very uncomfortable", value: 1 },
      { text: "Somewhat uncomfortable", value: 2 },
      { text: "Neutral", value: 3 },
      { text: "Comfortable", value: 4 },
      { text: "Very comfortable", value: 5 },
    ],
  },
  
  // Intelligence questions
  {
    id: "i1",
    attributeType: "intelligence",
    question: "How quickly do you typically solve complex problems?",
    options: [
      { text: "Very slowly", value: 1 },
      { text: "Slowly", value: 2 },
      { text: "Average speed", value: 3 },
      { text: "Quickly", value: 4 },
      { text: "Very quickly", value: 5 },
    ],
  },
  {
    id: "i2",
    attributeType: "intelligence",
    question: "How would you rate your ability to understand others' emotions and motivations?",
    options: [
      { text: "Poor", value: 1 },
      { text: "Below average", value: 2 },
      { text: "Average", value: 3 },
      { text: "Above average", value: 4 },
      { text: "Excellent", value: 5 },
    ],
  },
  {
    id: "i3",
    attributeType: "intelligence",
    question: "How good are you at coming up with creative solutions to problems?",
    options: [
      { text: "Not creative at all", value: 1 },
      { text: "Slightly creative", value: 2 },
      { text: "Moderately creative", value: 3 },
      { text: "Very creative", value: 4 },
      { text: "Extremely creative", value: 5 },
    ],
  },
  
  // Strength questions
  {
    id: "s1",
    attributeType: "strength",
    question: "How often do you engage in physical exercise?",
    options: [
      { text: "Rarely or never", value: 1 },
      { text: "1-2 times per month", value: 2 },
      { text: "1-2 times per week", value: 3 },
      { text: "3-5 times per week", value: 4 },
      { text: "6+ times per week", value: 5 },
    ],
  },
  {
    id: "s2",
    attributeType: "strength",
    question: "How would you rate your physical strength compared to others your age?",
    options: [
      { text: "Much weaker", value: 1 },
      { text: "Somewhat weaker", value: 2 },
      { text: "Average", value: 3 },
      { text: "Somewhat stronger", value: 4 },
      { text: "Much stronger", value: 5 },
    ],
  },
  {
    id: "s3",
    attributeType: "strength",
    question: "How quickly do you recover from physical exertion?",
    options: [
      { text: "Very slowly", value: 1 },
      { text: "Slowly", value: 2 },
      { text: "Average", value: 3 },
      { text: "Quickly", value: 4 },
      { text: "Very quickly", value: 5 },
    ],
  },
  
  // Health questions
  {
    id: "h1",
    attributeType: "health",
    question: "How would you rate your overall physical health?",
    options: [
      { text: "Poor", value: 1 },
      { text: "Fair", value: 2 },
      { text: "Good", value: 3 },
      { text: "Very good", value: 4 },
      { text: "Excellent", value: 5 },
    ],
  },
  {
    id: "h2",
    attributeType: "health",
    question: "How would you rate your mental/emotional wellbeing?",
    options: [
      { text: "Poor", value: 1 },
      { text: "Fair", value: 2 },
      { text: "Good", value: 3 },
      { text: "Very good", value: 4 },
      { text: "Excellent", value: 5 },
    ],
  },
  {
    id: "h3",
    attributeType: "health",
    question: "How healthy is your diet?",
    options: [
      { text: "Very unhealthy", value: 1 },
      { text: "Somewhat unhealthy", value: 2 },
      { text: "Average", value: 3 },
      { text: "Healthy", value: 4 },
      { text: "Very healthy", value: 5 },
    ],
  },
];
